<!DOCTYPE html>
<html>
<head>
    <title>Learning Analytics Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #111; margin: 20px; }
        h2 { margin-bottom: 10px; }
        p { margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; vertical-align: middle; }
        th { background: #f0f0f0; font-weight: bold; }
        tbody tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 20px; font-size: 10px; text-align: center; color: #666; font-weight: bold; }

        .progress-bar-container {
            width: 100%;
            background-color: #eee;
            border-radius: 4px;
            overflow: hidden;
            height: 14px;
        }
        .progress-bar-fill {
            height: 100%;
            background-color: #4f46e5; 
            text-align: right;
            color: white;
            font-size: 10px;
            line-height: 14px;
            padding-right: 4px;
        }
    </style>
</head>
<body>

<h2>Learning Analytics Report</h2>
<p><strong>Student:</strong> {{ $user->name }}</p>

<p><strong>Report Type:</strong> 
    @if(isset($reportType) && $reportType != 'All Courses')
        {{ $reportType }} 
    @else
        All Courses
    @endif
</p>

<p><strong>Generated:</strong> {{ now()->format('M d, Y') }}</p>

<table>
    <thead>
        <tr>
            <th>Course</th>
            <th>Completed Lessons</th>
            <th>Total Lessons</th>
            <th>Progress</th>
            <th>Quiz Attempts</th>
        </tr>
    </thead>
    <tbody>
        @forelse($analytics as $item)
            <tr>
                <td>{{ $item['course_title'] }}</td>
                <td>{{ $item['completed_lessons'] }}</td>
                <td>{{ $item['total_lessons'] }}</td>
                <td>
                    <div class="progress-bar-container">
                        @if($item['progress'] > 0)
                            <div class="progress-bar-fill" style="width: {{ $item['progress'] }}%;">
                                {{ $item['progress'] }}%
                            </div>
                        @endif
                    </div>
                </td>
                <td>{{ $item['quiz_attempts'] }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" style="text-align: center;">No data available</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Learning Analytics Report • Generated by LearnHub
</div>

</body>
</html>
